import { supabase } from '@/lib/supabase';
import { getTodayAttendanceSummary } from './attendanceUtils';

// Get admin contact info
export const getAdminContactInfo = async () => {
  try {
    const { data, error } = await supabase
      .from('admin_settings')
      .select('*')
      .single();

    if (error) {
      console.error('Error fetching admin contact info:', error);
      return {
        whatsapp_number: '',
        is_whatsapp_share_enabled: false,
        email: '',
        phone: '',
        whatsapp: '',
        telegram: '',
        notification_preferences: {
          email: false,
          sms: false,
          whatsapp: false,
          telegram: false
        }
      };
    }

    return data || {
      whatsapp_number: '',
      is_whatsapp_share_enabled: false,
      email: '',
      phone: '',
      whatsapp: '',
      telegram: '',
      notification_preferences: {
        email: false,
        sms: false,
        whatsapp: false,
        telegram: false
      }
    };
  } catch (error) {
    console.error('Error in getAdminContactInfo:', error);
    return {
      whatsapp_number: '',
      is_whatsapp_share_enabled: false,
      email: '',
      phone: '',
      whatsapp: '',
      telegram: '',
      notification_preferences: {
        email: false,
        sms: false,
        whatsapp: false,
        telegram: false
      }
    };
  }
};

// Save admin contact info
export const saveAdminContactInfo = async (whatsappNumber: string, isEnabled: boolean, info: any) => {
  try {
    const { data: existingData, error: fetchError } = await supabase
      .from('admin_settings')
      .select('id')
      .single();

    let result;
    if (existingData?.id) {
      // Update existing record
      result = await supabase
        .from('admin_settings')
        .update({
          whatsapp_number: whatsappNumber,
          is_whatsapp_share_enabled: isEnabled,
          whatsapp: whatsappNumber,
          updated_at: new Date().toISOString()
        })
        .eq('id', existingData.id);
    } else {
      // Insert new record
      result = await supabase
        .from('admin_settings')
        .insert({
          whatsapp_number: whatsappNumber,
          is_whatsapp_share_enabled: isEnabled,
          whatsapp: whatsappNumber,
          created_at: new Date().toISOString(),
          updated_at: new Date().toISOString()
        });
    }

    if (result.error) {
      throw new Error('Failed to save admin contact information');
    }

    return { success: true };
  } catch (error) {
    console.error('Error saving admin contact info:', error);
    throw error;
  }
};

// Auto share attendance summary
export const autoShareAttendanceSummary = async () => {
  try {
    const [summary, adminInfo] = await Promise.all([
      getTodayAttendanceSummary(),
      getAdminContactInfo()
    ]);

    if (!adminInfo.is_whatsapp_share_enabled || !adminInfo.whatsapp_number) {
      console.log('WhatsApp sharing is disabled or no number configured');
      return false;
    }

    const formattedDate = new Date().toLocaleDateString('en-US', { 
      weekday: 'long', 
      year: 'numeric', 
      month: 'long', 
      day: 'numeric',
      hour: '2-digit',
      minute: '2-digit'
    });

    const message = 
`🏢 *ATTENDANCE REPORT*
━━━━━━━━━━━━━━━━━━━━━
📅 ${formattedDate}
━━━━━━━━━━━━━━━━━━━━━

📊 *SUMMARY*
• Total Employees: ${summary.totalEmployees}
• Present: ${summary.presentCount} 👥
• Late: ${summary.lateCount} ⏰
• Absent: ${summary.absentCount} ❌
• Checked Out: ${summary.checkedOutCount} 🏃

📈 *RATES*
• Attendance Rate: ${summary.totalPresentRate}%
• Late Rate: ${summary.lateRate}%
• Absence Rate: ${summary.absentRate}%

Generated by QR Attendance System
Time: ${new Date().toLocaleTimeString()}
━━━━━━━━━━━━━━━━━━━━━`;

    const number = adminInfo.whatsapp_number.trim().replace(/\D/g, '');
    const formattedNumber = number.startsWith('0') 
      ? '94' + number.substring(1)
      : number.startsWith('94') 
        ? number 
        : '94' + number;

    const encodedMessage = encodeURIComponent(message);
    const whatsappUrl = `https://api.whatsapp.com/send?phone=${formattedNumber}&text=${encodedMessage}`;
    
    return whatsappUrl;
  } catch (error) {
    console.error('Error in autoShareAttendanceSummary:', error);
    return false;
  }
};

